export default {
    carRentalMenu: '[data-id="IcProductDuotoneCarRentalFill"]',
    withoutDriver: '[data-id="IcTransportPickUpDriver"]',
    locationInput: '[data-testid="rental-search-form-location-input"]',
    resultLocation: '[data-testid="rental-search-form-location-item"]',
    datePickerPickup: '[data-testid="rental-search-form-date-input-start"]',
    timePickerPickup: '[data-testid="rental-search-form-time-input-start"]',
    timePickerDoneButton: '//div[contains(text(), "Done")]',
    datePickerDrop: '[data-testid="rental-search-form-date-input-end"]',
    containerDatePicker: `/html/body/div[1]/div[4]/div[2]/div[1]/div[2]/div/div[3]/div/div/div/div/div[2]/div/div[7]/div/div[2]/div/div/div/div`,
    timePickerDrop: '[data-testid="rental-search-form-time-input-end"]',
    searchCarButton: '[data-testid="rental-search-form-cta"]',
    selectCarFirstOption: "(//div[contains(@role, 'button')][contains(.,'Continue')])[1]",
    rentalPickupContainer: "RENTAL_PICKUP_LOCATION",
    rentalPickupOfficeButton:  "//div[contains(text(), 'Rental Office')]/ancestor::div[@role='radio']",
    rentalOfficeDropdown:  "/html/body/div[1]/div/div[5]/div/div[1]/div/div[3]/div[1]/div/div/div[3]/div[2]/div/div/div[1]/div[1]/div/div[2]/img",
    officeAddressData:  "/html/body/div[1]/div/div[5]/div/div[1]/div/div[3]/div[1]/div/div/div[3]/div[2]/div/div/div[1]/div[2]/div/div/div/div[1]/div[1]/div/div[1]/div/div[2]",
    rentalDropOffContainer: "RENTAL_DROPOFF_LOCATION",
    otherLocationsRadio: "/html/body/div[1]/div/div[5]/div/div[1]/div/div[3]/div[2]/div/div/div[5]/div[1]/div[2]/div",
    textAreaNotePickup: 'textarea[placeholder="Additional notes (optional)"]',
    bookNowButton:"/html/body/div[1]/div/div[5]/div/div[1]/div/div[5]/div[3]",
    fullNameFormContact: "//label[@id='name.full']/following-sibling::div//input",
    phoneFormContact: "//label[@id='Mobile Number,[object Object]']/following-sibling::div//input",
    emailFormContact: "//label[@id='emailAddress']/following-sibling::div//input",
    driverFormContainer: "adultForm0",
    fullNameFormDriver: ".//label[@id='name.full']/following-sibling::div//input",
    phoneFormDriver: ".//label[@id='Mobile Number,[object Object]']/following-sibling::div//input",
    dropdownTitle: "/html/body/div/div[2]/div[2]/div[1]/div[3]/div/div/div/div/div/div/div[2]/div[1]/div/div[1]/select",
    continueButtonRentalDetail: `/html/body/div/div[2]/div[2]/div[1]/div[4]/div/div`,
    specialRequestTextArea:  'textarea[placeholder="Odd or even license plates, car charger, baby car seat, etc."]',
    checkRequirementButton: '[data-id="IcSystemChevronRight"]',
    checkAll: `/html/body/div[2]/div/div[2]/div/div[2]/div/div[1]/div[2]`,
    saveButton: "(//div[contains(@role, 'button')][contains(.,'Save')])",
    continuePayment:  "(//div[contains(@role, 'button')][contains(.,'Continue to Payment')])",
    continueConfirmation:  "html body div div.css-1dbjc4n.r-1niwhzg.r-1p0dtai.r-6koalj.r-1d2f490.r-1xcajam.r-zchlnj.r-ipm5af div.css-1dbjc4n.r-1kihuf0.r-13awgt0.r-1777fci.r-crgep1.r-nsbfu8.r-12vffkv.r-13qz1uu div.css-1dbjc4n.r-14lw9ot.r-kdyh1x.r-da5iq2.r-1udh08x.r-nsbfu8 div.css-1dbjc4n.r-1wzrnnt div.css-1dbjc4n.r-1oszu61.r-eqz5dr div.css-18t94o4.css-1dbjc4n.r-kdyh1x.r-1loqt21.r-10paoce.r-1e081e0.r-5njf8e.r-1otgn73.r-lrvibr div.css-1dbjc4n.r-1awozwy.r-13awgt0.r-18u37iz.r-1777fci div.css-901oao.css-bfa6kz.r-jwli3a.r-t1w4ow.r-cygvgh.r-b88u0q.r-1iukymi.r-q4m81j",
    transferMenu:`[data-testid="paymentOption-TRANSFER"]`,
    payWithTransferButton: `[data-testid="payNowButtonText-Pay with Bank Transfer-TRANSFER"]`,
    paymentInstructionLabel: `[data-testid="paymentInstructionContainer"]`,
    transferAmountLabel: `[data-testid="transferAmount"]`
    // Add other element IDs as needed
};

